In [2]:
#In your numpy-pandas-visualization-exercises repo, create a file named numpy_exercises.py for this exercise.

#Use the following code for the questions below:

import numpy as np
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [3]:
# Exercise 1
# How many negative numbers are there?

(a<0).sum()


4

In [113]:
# Exercise 2
# How many positive numbers are there?

(a>0).sum()

5

In [5]:
# Exercise 3
# How many even positive numbers are there?


pos_and_even_num = (a > 0) & (a % 2 == 0)
print((pos_and_even_num).sum())

3


In [115]:
# Exercise 4
# If you were to add 3 to each data point, how many positive numbers would there be?

add_three = (a + 3) 
(add_three > 0).sum()

10

In [37]:
# Exercise 5
# If you squared each number, what would the new mean and standard deviation be?

num_squared = a ** 2
print (num_squared)
num_squared.std(), num_squared.mean()

[ 16 100 144 529   4   1   0   0   0  36   9  49]


(144.0243035046516, 74.0)

In [116]:
# Exercise 6
# A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

centering = a - a.mean()
centering.mean()


0.0

In [117]:
# Exercise 7
# Calculate the z-score for each data point. Recall that the z-score is given by:

(a - a.mean()) / a.std()

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [118]:
# Exercise 8
# Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.

# Life w/o numpy to life with numpy

## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [49]:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

sum_of_a = sum(a)
sum_of_a

55

In [50]:
#Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list
min_of_a = min(a)
min_of_a

1

In [119]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list
max_of_a = max(a)
max_of_a

10

In [120]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list
mean_of_a = sum(a) / len(a)
mean_of_a

5.5

In [60]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list

product_of_a = 1

for x in a:
    product_of_a = product_of_a * x

product_of_a

3628800

In [121]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

squares_of_a = [a**2 for a in a]
squares_of_a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [62]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

odds_in_a = [a for a in a if a % 2 != 0]
odds_in_a

[1, 3, 5, 7, 9]

In [122]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

evens_in_a = [a for a in a if a % 2 == 0]
evens_in_a

[2, 4, 6, 8, 10]

In [123]:
## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]


In [124]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)
    
b = np.array(b)
b.sum()

33

In [67]:
# Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

b = np.array(b)
b.min()

3

In [69]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

b = np.array(b) #don't need to turn into array for every problem
b.max()

8

In [125]:
# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

b.mean()

5.5

In [71]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

b.prod()

20160

In [127]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)
    
b**2

array([[ 9, 16, 25],
       [36, 49, 64]])

In [129]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)

b[b % 2 != 0]

array([3, 5, 7])

In [130]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)

b[b % 2 == 0]

array([4, 6, 8])

In [131]:
# Exercise 9 - print out the shape of the array b.

b.shape

(2, 3)

In [88]:
# Exercise 10 - transpose the array b.
#b.T also works 
np.transpose(b)

array([[3, 6],
       [4, 7],
       [5, 8]])

In [86]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)
# np.reshape(b, (1, 6) also works
b.flatten()

array([3, 4, 5, 6, 7, 8])

In [90]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

# HINT, you'll first need to make sure that the "c" variable is a numpyarray prior to using numpy array methods.

np.reshape(b, (6, 1))

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [135]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# HINT, you'll first need to make sure that the "c" variable is a numpy
# DONT FORGET TO TURN C INTO AN ARRAY

In [136]:
# Exercise 1 - Find the min, max, sum, and product of c.
c = np.array(c)
c.min(), c.max(), c.sum(), c.prod()



(1, 9, 45, 362880)

In [137]:
# Exercise 2 - Determine the standard deviation of c.
c.std()

2.581988897471611

In [138]:
# Exercise 3 - Determine the variance of c.
np.var(c)

6.666666666666667

In [139]:
# Exercise 4 - Print out the shape of the array c
c.shape

(3, 3)

In [140]:
# Exercise 5 - Transpose c and print out transposed result.
c.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [133]:
# Exercise 6 - Get the dot product of the array c with c. 
np.dot(c,c).sum()

729

In [141]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261
(np.dot(c, c.T)).sum()

693

In [ ]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.


In [153]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

np.array(d)

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

In [ ]:
# Exercise 1 - Find the sine of all the numbers in d

In [154]:
# Exercise 2 - Find the cosine of all the numbers in d
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [150]:
# Exercise 3 - Find the tangent of all the numbers in d
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [156]:
# Exercise 4 - Find all the negative numbers in d


TypeError: '<' not supported between instances of 'list' and 'int'

In [ ]:
# Exercise 5 - Find all the positive numbers in d

In [ ]:
# Exercise 6 - Return an array of only the unique numbers in d.

In [ ]:
# Exercise 7 - Determine how many unique numbers there are in d.

In [ ]:
# Exercise 8 - Print out the shape of d.

In [ ]:
# Exercise 9 - Transpose and then print out the shape of d.

In [ ]:
# Exercise 10 - Reshape d into an array of 9 x 2